### ISSUE TITLE
v3.1 Import/Export Breakdown with Delimiter Invalidation in Snips

### ISSUE THREAD

**Issue by iWrote** [GaurangTandon/ProKeys#20]
Delimiters make import/export completely dysfunctional. Users can't keep track of all that. I exported a snip with " in it (while " was a delimiter). I couldn't import it.
What would happen when a user exports 10 snippets with hyphens in them. A month later he adds hyphen as a delimiter. 
Fails to import his snippets and rage quits.

**Comment by iWrote** [comment]
Possible Solutions:
a> Reduce the valid character data-set for snippets. (Not to keen on that one.)
b> Let users choose a character to replace the invalid character during import/export.

**Comment by iWrote** [comment]
b> I think you were right. It's best to limit the valid character set for snippet names.
(They can still be used in the body, right?)

There is no other way to strike a reasonable balance. Letting the users choose breaks import/export.

**Comment by GaurangTandon** [comment]
*draft-wip*

Let's just decide this for good:

## Why we need match whole word property?

Many users create snippets like "cat", "dog" and then a combination of the two like "catdog" and expect to expand "catdog" instead of just "dog" (Refer email by Audrey). Other users create snippets like "y", "yy" and "yyy" pertaining to the year and then expect to expand "yyy" instead of "y" (refer email jacky chan).

## Are there any other solutions to this documented problem?

Yes, we could start matching snip names 30 characters (<--name lelimit)

**Comment by GaurangTandon** [comment]
@iWrote Your thoughts about the other solution?

**Comment by iWrote** [comment]
Yeah! Limit the maximum length of snippet names to 20 characters and check for 25 characters before the cursor. Should work well. 

**But that just solves the problem of yyy vs yy.**  

Carpet would still become Carpug, right? Delimiters are still haunting us :cry:

**Comment by GaurangTandon** [comment]
Ok, so there are TWO problems that need to be solved:

1. **Unintended snip name as a part of a non-snip name word** - like "carpet" (non-snip) containing "pet" (snip name) and becoming "carpug" when it shouldn't.
2. "Snip names part of longer snip name getting expanded" - like in "foobar", "bar" getting expanded instead of the "foobar".

_WIP_

**Comment by iWrote** [comment]
Match longer snip first solves the problem. Closed 2.

Now we're back to - How do we mesh import/export with delimiters' character invalidation?

**Comment by GaurangTandon** [comment]
Let's chalk out that feature in detail:

1. **Delimiters** - a custom user editable list of single characters that separate two snip names.
2. Since delimiters separate snip names, it isn't logical to allow them to be used inside a snippet name.
3. **What would happen if delimiters were used inside snip name?** Well, nothing, because not allowing them in snip name is a logical step but not a forced one. Reverting point 2 does nothing bad, but it's illogical.

### Problem Scenario 1:

User creates 10 snips, all with a hyphen in it. He later enables match whole word property. A month later, he imports those snippets but is unable to do so as the hyphens (a delimiter) are marked invalid. He will possibly forget that he ever had enabled match whole word property, become enraged that import isn't working, and quit ProKeys, forever.

**Solution:** Allow delimiters to be used in a snip name. But this contradicts point 2, which isn't impossible, but illogical.

**Solution2:** Allow option, if this situation arises, to replace the invalid character with some other character in all instances of the problem.

## Final decision:

What do you think @iWrote ?

**Comment by GaurangTandon** [comment]
> Solution2 will work, but isn't ideal. Users won't like changing snippet names, they might get used to typing some with the old names, 

Hmmm, yes you're right.

> It's time to limit the valid character set for snippet names. Make it alphanumeric. No special characters whatsoever.

But, how will you separate two words as a part of snip name, like, how will you write "boss-sign"? Users won't like to press Shift every time to write "bossSign"...

We can go with Soluition1 then?

**Comment by iWrote** [comment]
Best I could come up with.

If you enable match longer snip, then the delimiter issues can be solved easily by disallowing users to **start or end snip name with special characters.** They can totally use them in the middle. 

That should work, right?

**Comment by GaurangTandon** [comment]
I intend to discuss this with you in school, possibly during the zero/ped/lunch period. This topic is just so confusing.

**Comment by iWrote** [comment]
Okay.

P.S. Why does GitHub let me edit YOUR comments?

**Comment by GaurangTandon** [comment]
You are the collaborator here ;) Didn't notice that badge?

![image](https://cloud.githubusercontent.com/assets/6308683/16840210/19cd4a24-49f1-11e6-93d9-e1ae1bd9fa16.png)

It's got more power to it than you might have previously thought ;)

**Comment by iWrote** [comment]
So we're doing both - 

 [ ] Match longer snip name first?
 [ ] Match whole word?

Right?

Don't know why I didn't do this before, gonna go hit PopChrom and others with all these edge-cases.

**Comment by GaurangTandon** [comment]
**Let's recapitulate:**

There were two problems that needed to be solved. 

1. Unintended snip name as a part of a non-snip name word - like "carpet" (non-snip) containing "pet" (snip name) and becoming "carpug" when it shouldn't.
2. Short snip name, as a part of longer snip name, getting expanded - like in "foobar", "bar" getting expanded instead of the "foobar".

2nd problem is solved by matching longer snip names first. This is a default feature and not editable by user.

For the first problem, we need delimiters. Delimiters are special characters that will separate snippet names. It is a user editable list. By default, it is all the symbols the top-keyboard row can provide. Delimiters can be used inside snippet names (we've discussed above why we need to do so)

So, we're good on this issue now?

**Comment by GaurangTandon** [comment]
Ok, so final implementation is as follows:

1. `matchWholeWord` is not a editable property and is default.
2. Two new properties `matchDelimiterWord` and `delimiterList` have been introduced - both of which are user-editable boolean and string respectively.

@iWrote do you have suggestions for the default list of delimiters? Currently, it is this: `,.+=!@#%^&*()[]{}\\/\"'|<>~``

**Comment by iWrote** [comment]
We're not including ` _ ` ? 

If we include `! `then we must include `? :  ; `


Let's reserve - ` \ | `

**Comment by GaurangTandon** [comment]
Any rational reasons for your decisions? As for my original list, it was the first thought that came to my mind and hence awaits changes.

**Comment by iWrote** [comment]
Okay. Here's the list I recommend -

**Use** - ` @ # $ % & * + - = ( ) { } [ ] : " ' / _  <>`  

and maybe these ` ? ! , . ` 

**Reserve**  - ` (backtick)  ~ | \ ^`

**Why** -
1. Punctuation has a space after it, so I felt that it doesn't need to be a delimiter. But perhaps we should add it as well.

2. Reserved words are not used that often. We have to reserve some characters. It MIGHT make someone unhappy but some words need to be reserved.

3. The first list has all the characters which regularly hug snips. It makes sense to add them by default.

4. We don't need to worry _too_ much. The delimiter list IS customisable. Will need explanation, though.

**Comment by GaurangTandon** [comment]
Ok, will add this list. Will do the final testing tomorrow and release in 2-3 days.

**Comment by GaurangTandon** [comment]
I just realised that test for delimiter presence is NOT being done by `detector.js`. Have to do that first. As of now, `carpet` is expanding to `carpug`.

**Comment by GaurangTandon** [comment]
I am also adding the punctuation marks because they're very frequently used to mark the end of sentences where our users are most likely to expand snippets.

**Comment by GaurangTandon** [comment]
As of now, `carbrb` doesn't expand but `brb`, ` brb` and `.brb` all do. Thanks! The issue is finally closed.
