### ISSUE TITLE
'choose file containing data'

### ISSUE THREAD

**Issue by agondawhitesand** [GaurangTandon/ProKeys#39]
**Browser name:** - Chrome
**OS name:** - chrome
**Site** where ProKeys is functioning improperly - %site_url%
**Description:** I have installed ProKeys into chrome on a windows 10 pc. When I select "import/Restore" and I am given the prompt to choose a file to upload, I click this link and nothing happens. If I right click and choose open link, it just takes me to a settings page. On my mac with chrome it open the file chooser. Please give me some advice on what maybe causing this issue on my pc and what I can do. BTW I have already cleaned off chrome and Prokeys twice and reinstalled, but this made no difference.

Thank you

**Comment by GaurangTandon** [comment]
I am surprised how this issue got missed. Will fix it in the next release. Thanks for posting! 

In fact, if it works on a Mac, this is a rather very surprising issue,

**Comment by agondawhitesand** [comment]
Dear Gaurang,

Thank you for you for your email.

The app is amazing if you are on a computer all day doing boring emails.

I am sorry to trouble you with this question. How often do you do updates?
And is there another way I can access the app to add my backup?

Warm regards


Warm regards


John
www.agondawhitesand.com
info@agondawhitesand.com
Part of the Vilasaahuta™ group

**Comment by GaurangTandon** [comment]
Well, actually, to be honest the update for 3.1.0 has been pending for at least a month and I am sorry to say that this will remain pending for a month as well. I am very sorry but please try to understand that I have some important exams going on due to which I am unable to give time to ProKeys. Although, I am not taking up any new projects and ProKeys is still my top priority as soon as I get free time.

For your second question, I'm still surprised that this issue exists in the first place. Perhaps, this is because of the recent update to Chrome because I am 100% sure I had tested this many many times when released. For now, you may paste this code in the Chrome console that pops up when you press F12 on the Options page, like this:

![image](https://cloud.githubusercontent.com/assets/6308683/18546864/f4f78dd8-7b5d-11e6-9789-3610363cfc21.png)


Code:

```
var textData = '(all your data inside these single quotes)';
var json = JSON.parse(textData); 
var snps = Folder.fromArray(json); 
Folder.copyContents(snps, Data.snippets);
saveSnippetData();
```

The inconvenience is deeply regretted. Thank you for your patience!

**Comment by agondawhitesand** [comment]
Dear Gaurang,


Thank you for getting back to me and best of luck with your exams.

I found a solution.

I was able to download a only snippets back up and enter it into the edit
box of the past revisions. Yeah.

Thank you for a great extension.

Warm regards


​Mark
www.agondawhitesand.com
info@agondawhitesand.com
Part of the Vilasaahuta™ group

**Comment by GaurangTandon** [comment]
Oh great, I missed that entirely.  If you have any more feedback, please don't hesitate in filing new issues here. Thanks!

**Comment by GaurangTandon** [comment]
Fixed in local branch. Will reflect in next public update.

**Solution:** Was to use a `label`+`input` combination. `trigger("click")` was not working maybe because of security restrictions.

@agondawhitesand Thank you once again for reporting the bug :)
